### ISSUE TITLE
Project license for use and contributions

### ISSUE THREAD

**Issue by terrehbyte** [zolo/editorzoom#3]
Howdy! You indicated in your README that you're open to contributions to this repository but haven't provided any sort of license for this project, which makes it difficult to contribute since you haven't granted any ability to make any modifications to your work.

Would you be able to provision this project with one? You can check [GitHub's docs for a more detailed explanation](https://help.github.com/articles/licensing-a-repository/) why you'd need one.

**Comment by zolo** [comment]
Thanks for the suggestion. The May release of VS Code supports everything this plugin does. Hence, this project is no longer maintained
